### ISSUE TITLE
About the Paper

### ISSUE THREAD

**Issue by AFEICHINA** [StephLin/KCP#1]
Hi! Lin
    Thanks for sharing your great works.
    If possible, can your share the preprint paper in docs?
    Best regards

**Comment by StephLin** [comment]
Dear Afei,

Thanks for your interest! We have uploaded the preprint [here](https://gpl.cs.nctu.edu.tw/Steve-Lin/KCP/preprint.pdf). Please take a look 😉

Cheers,
Yu-Kai
