### ISSUE TITLE
How can I use it for scan to map step ?

### ISSUE THREAD

**Issue by qpc001** [StephLin/KCP#2]

**Comment by StephLin** [comment]
Hi @qpc001,

KCP is originally designed for scan-to-scan matching. In terms of your case (I suppose that your map is a union of several scans), there is a possible trick that you may give it a try:

1. Compute corner points for each scan of the map. Note that you should use the scan coordinate to compute corner points.
2. Compute the union of the above corner points of all scans using their global coordinates.

In this way you can obtain a "corner-point cloud" of the map. Try to use KCP with the cloud and the corner-point cloud of the scan.

Best,
StephLin

**Comment by StephLin** [comment]
Feel free to reopen it if you have other concerns. Thanks!
