### ISSUE TITLE
Could it apply to 2d point cloud registration

### ISSUE THREAD

**Issue by narutojxl** [StephLin/KCP#5]
Hello author,
Thanks for your sharing  excellent work to community!
* Could we apply KCP to a 2d point cloud registration problem ?
* If we can, does KCP need user to provide point cloud correspondences? Teaser++ does not support pure 2D transformation, and it also needs user to generate the correspondences, [here](https://github.com/MIT-SPARK/TEASER-plusplus/issues/119#issuecomment-962066155) 

Thanks for your help.

**Comment by narutojxl** [comment]
From the test result, KCP(kcp::keypoint::MultiScaleCurvature()) seems doesn't support 2d point cloud. KCP doesn't need [user given correspondences](https://github.com/StephLin/KCP/blob/main/examples/cpp/main.cpp)

**Comment by StephLin** [comment]
Hi @narutojxl,

Thanks for your questions!

Unfortunately KCP does not support 2-D registration as [TEASER++ (the algorithm we used in KCP) does not support it yet](https://github.com/MIT-SPARK/TEASER-plusplus/issues/119).

By default, KCP does not require user-defined point correspondences as we compute feature points and their correspondences automatically in KCP. However, you can feed your customized feature points ([C++](https://github.com/StephLin/KCP/blob/main/examples/cpp/main.cpp#L78-L82), [Python](https://github.com/StephLin/KCP/blob/main/examples/python/main.py#L176-L178)). Also, you can even change the feature space used for nearest neightbor searching in KCP ([C++](https://github.com/StephLin/KCP/blob/main/examples/cpp/main.cpp#L95), [Python](https://github.com/StephLin/KCP/blob/main/examples/python/main.py#L190-L191)).

Sorry for the late reply, and hope it helps.
